(() => {
  "use strict";
  const V="20.7.10",d=document,$=(s,r=d)=>r.querySelector(s),C=v=>String(v??"").replace(/\s+/g," ").trim(),L=v=>C(v).toLowerCase(),E=v=>C(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c])),U=v=>/^https?:\/\//i.test(C(v)),P=new URLSearchParams(location.search);
  const BLOCK=new Set(["temu","joom","filamentpro","filamentpro eu cps"]);
  const FILE={phone:"phone",laptop:"laptop",perfume:"perfume",smartwatch:"smartwatch",headphones:"headphones",power_bank:"power_bank",dog_food:"dog_food",air_conditioner:"air_conditioner","3d_filament":"3d_filament",cookware:"cookware",lighting:"lighting",tools:"tools"};
  const LABEL={phone:"Phone",laptop:"Laptop",perfume:"Fragrance",smartwatch:"Smart watch",headphones:"Audio",power_bank:"Power bank",dog_food:"Dog food",air_conditioner:"Air conditioner","3d_filament":"3D filament",cookware:"Cookware",lighting:"Lighting",tools:"Tools"};
  const BROAD={phone:/^(?:pho|phon|phone|phones|smartp|smartph|smartpho|smartphon|smartphone|smartphones|mobile phone|mobile phones|cell phone|cell phones)$/i,laptop:/^(?:lap|lapt|lapto|laptop|laptops|notebook|notebooks)$/i,perfume:/^(?:per|perf|perfu|perfum|perfume|perfumes|frag|fragr|fragra|fragrance|fragrances)$/i,smartwatch:/^(?:watch|watches|smartwatch|smart watch|smartw|smartwa|smartwatc)$/i,headphones:/^(?:headphone|headphones|headset|headsets|earbud|earbuds|earphone|earphones|audio)$/i,power_bank:/^(?:power bank|power banks|powerbank|powerbanks)$/i,dog_food:/^(?:dog food|dog foods|puppy food)$/i,air_conditioner:/^(?:air conditioner|air conditioners|portable ac|mini split)$/i,"3d_filament":/^(?:3d filament|filament|pla filament|petg filament|abs filament)$/i,cookware:/^(?:cookware|pots and pans|pots|pans)$/i,lighting:/^(?:lighting|lights|lamps|bulbs)$/i,tools:/^(?:tool|tools)$/i};
  const PF=/\b(?:accessor(?:y|ies)|case|cases|cover|covers|shell|bumper|pouch|sleeve|screen protector|tempered glass|protective glass|protective film|film protector|sim(?: card)? tray|sim holder|sim slot|replacement battery|battery for|bateria for|phone battery|battery case|replacement|repair|spare part|charging port|wireless charger|phone charger|wall charger|car charger|charging station|charging cable|charging cord|usb cable|usb cord|data cable|data cord|cable|cord|connector|flex cable|digitizer|lcd replacement|display assembly|screen assembly|motherboard|back glass|housing|phone holder|phone stand|phone mount|car mount|bracket|tripod|selfie stick|strap|lanyard|wallet|game controller|gamepad|joystick|trigger|game handle|cooler|cooling fan|mini fan|fan\b|power bank|earbuds?|earphones?|headphones?|headsets?|smart ?watch|tablet|ipad|ssd enclosure|m\.?2 enclosure|adapter|dongle|dock|telescope|telephoto|monocular|binocular|microscope|camera lens|lens kit|ring light|stylus|keyboard|carplay|holder stand|packing box|phone box|empty box|sticker|skin|cleaning kit|repair tool|opening tool|suction cup|adhesive|glue)\b/i;
  const FIT=/\b(?:for|fits?|compatible with|replacement for|used for|suitable for)\s+(?:(?:apple|samsung|google|xiaomi|redmi|oneplus|poco|oppo|vivo|realme|motorola|moto|honor|huawei|nokia|sony|zte)\s+)?(?:iphone|galaxy|pixel|android(?:\s+mobile)?\s+phone|mobile phone|cell phone|smartphone)\b/i;
  const PM=/\b(?:iphone\s*(?:[5-9x]|1[0-9])(?:\s*(?:pro|max|plus|mini|e|s|se))?|samsung\s+galaxy\s+[a-zmfsz]\s*\d+|galaxy\s+(?:s|a|m|f|z)\s*\d+|google\s+pixel\s+\d+|pixel\s+\d+|oneplus\s+\d+[a-z]?(?:\s+pro)?|xiaomi\s+(?:mi\s+)?\d+[a-z]?(?:\s+pro)?|redmi\s+(?:note\s+)?[a-z0-9]+|poco\s+[a-z]\d+|oppo\s+[a-z0-9]+|vivo\s+[a-z0-9]+|realme\s+[a-z0-9]+|motorola\s+(?:moto\s+)?[a-z0-9]+|moto\s+[a-z0-9]+|honor\s+[a-z0-9]+|huawei\s+(?:mate|p|nova)\s*\d+|nokia\s+[a-z0-9.]+|sony\s+xperia\s+[a-z0-9]+|nothing\s+phone\s*\(?\d+\)?|asus\s+(?:rog\s+phone|zenfone)\s*\d+|zte\s+[a-z0-9]+|nubia\s+[a-z0-9]+|infinix\s+[a-z0-9]+|tecno\s+[a-z0-9]+)\b/i;
  const PG=/\b(?:smart ?phone|mobile phone|cell phone|feature phone|android phone|android mobile phone|unlocked phone|gsm phone|5g phone|4g phone)\b/i;
  const PS=/\b(?:\d(?:\.\d+)?\s*(?:inch|inches|")|dual sim|single sim|gsm|cdma|5g|4g|lte|android\s*\d*|snapdragon|dimensity|helio|octa[- ]?core|quad[- ]?core|\d+\s*gb\s*ram|\d+\s*gb\s*(?:rom|storage)|\d{3,5}\s*mah|\d+\s*mp|camera|face unlock|fingerprint|keypad|touchscreen|full screen)\b/ig;
  const R={laptop:[/\b(?:laptop|notebook pc|notebook computer|chromebook|thinkpad|ideapad|thinkbook|macbook|vivobook|zenbook|probook|elitebook|latitude|inspiron|xps|legion|surface laptop|lenovo slim|gaming notebook)\b/i,/\b(?:case|sleeve|bag|stand|dock|docking station|charger|adapter|skin|replacement battery|replacement keyboard|replacement screen|hinge|keyboard cover|screen protector|sticker|planner|journal|cooling pad|laptop fan|cable)\b/i],perfume:[/\b(?:perfume|fragrance|cologne|eau de parfum|eau de toilette|parfum|edp|edt|extrait de parfum)\b/i,/\b(?:organizer|display stand|storage rack|bottle holder|empty perfume bottle|empty bottle|empty atomizer|room spray|car perfume|diffuser|refillable bottle)\b/i],smartwatch:[/\b(?:smart ?watch|apple watch|wearable watch|fitness watch|gps watch)\b/i,/\b(?:band|strap|case|cover|protector|charger|charging dock|dock|stand|replacement screen)\b/i],headphones:[/\b(?:headphones?|headsets?|earbuds?|earphones?|airpods?|tws|bluetooth audio)\b/i,/\b(?:case|cover|replacement earpads?|ear pads?|replacement cable|headphone stand|headset stand|charging case only|ear tips?)\b/i],power_bank:[/\b(?:power ?bank|portable charger|external battery|battery pack)\b/i,/\b(?:case|cover|cable only|usb cable|charging cable|adapter only|holder|pouch)\b/i],dog_food:[/\b(?:dog food|puppy food|canine food|dog treats?|dog snack|puppy treats?)\b/i,/\b(?:feeder|feeding machine|bowl|container|food dispenser|food preparation machine|pet appliance)\b/i],air_conditioner:[/\b(?:air conditioner|portable ac|mini split|split ac|ductless ac|window ac|air conditioning unit)\b/i,/\b(?:cover|remote control|filter replacement|spare part|capacitor|compressor part|drain hose|mounting bracket|cleaning bag)\b/i],"3d_filament":[/\b(?:3d filament|pla filament|petg filament|abs filament|tpu filament|nylon filament|filament 1\.75|filament 2\.85)\b/i,/\b(?:3d printer|filament dryer|dry box|extruder|nozzle|hotend|spool holder|storage box)\b/i],cookware:[/\b(?:cookware|frying pan|saucepan|stockpot|casserole|wok|skillet|cooking pot|pan set|pot set)\b/i,/\b(?:replacement handle|lid only|cover only|pan protector|rack|organizer)\b/i],lighting:[/\b(?:lamp|lighting|light fixture|led light|led strip|bulb|ceiling light|wall light|desk lamp|floor lamp)\b/i,/\b(?:remote control only|controller only|adapter only|cable only|connector only|mounting clip)\b/i],tools:[/\b(?:tool set|hand tool|power tool|drill|saw|wrench|screwdriver|pliers|multimeter|oscilloscope|soldering iron|grinder|router|ratchet|socket set)\b/i,/\b(?:replacement battery only|charger only|case only|storage bag only)\b/i]};
  const FLOOR={phone:10,laptop:50,perfume:3,smartwatch:8,headphones:3,power_bank:3,dog_food:1,air_conditioner:30,"3d_filament":3,cookware:3,lighting:1,tools:1};
  const S={type:"",q:"",raw:[],list:[],i:0,shown:[],size:18,busy:false,buckets:new Map(),generic:false};
  const seller=n=>{n=L(n);return !!n&&!BLOCK.has(n)},broad=(q,t)=>!!(t&&BROAD[t]?.test(C(q))),tokens=q=>L(q).replace(/[^a-z0-9]+/g," ").split(/\s+/).filter(x=>x.length>1&&!["for","the","and","with","from","best","buy"].includes(x));
  const goodImage=v=>U(v)&&!/(?:no[-_ ]?(?:photo|image)|placeholder|image[-_ ]?not[-_ ]?available|default[-_ ]?(?:product|image)|blank[-_ ]?image|missing[-_ ]?image)/i.test(L(v));
  const type=q=>{q=L(q);if(BROAD.phone.test(q)||/\b(?:iphone|galaxy|pixel|oneplus|xiaomi|redmi|poco|oppo|vivo|realme|motorola|moto|honor|huawei|nokia|xperia|nothing phone|zenfone|nubia|infinix|tecno)\b/i.test(q))return"phone";if(BROAD.laptop.test(q)||/\b(?:thinkpad|ideapad|thinkbook|chromebook|macbook|vivobook|zenbook|probook|elitebook|latitude|inspiron|xps|legion|surface laptop|lenovo slim)\b/i.test(q))return"laptop";if(BROAD.perfume.test(q)||/\b(?:cologne|eau de parfum|eau de toilette|edp|edt)\b/i.test(q))return"perfume";if(BROAD.smartwatch.test(q)||/\b(?:apple watch|wearable watch)\b/i.test(q))return"smartwatch";if(BROAD.headphones.test(q)||/\b(?:airpods?|tws)\b/i.test(q))return"headphones";if(BROAD.power_bank.test(q)||/\b(?:portable charger|external battery)\b/i.test(q))return"power_bank";if(BROAD.dog_food.test(q)||/\b(?:dog treats?|canine food)\b/i.test(q))return"dog_food";if(BROAD.air_conditioner.test(q)||/\b(?:ductless ac|split ac)\b/i.test(q))return"air_conditioner";if(BROAD["3d_filament"].test(q)||/\b(?:petg|pla|abs|tpu)\s+filament\b/i.test(q))return"3d_filament";if(BROAD.cookware.test(q)||/\b(?:frying pan|saucepan|casserole|wok|skillet)\b/i.test(q))return"cookware";if(BROAD.lighting.test(q)||/\b(?:led strip|desk lamp|floor lamp|ceiling light)\b/i.test(q))return"lighting";if(BROAD.tools.test(q)||/\b(?:drill|saw|multimeter|oscilloscope|screwdriver|wrench)\b/i.test(q))return"tools";return""};
  const suffix=id=>(C(id).match(/^TP[A-Z]{2,8}-([A-Z0-9]{8,})$/i)||[])[1]?.toLowerCase()||"";
  async function meta(id){const x=suffix(id);if(!x)return null;const b=x.slice(0,2);if(!S.buckets.has(b))S.buckets.set(b,fetch(`/data/shopper-v20-6-8-4/products/${b}.json?v=${V}`,{cache:"no-store"}).then(r=>r.ok?r.json():null).catch(()=>null));return(await S.buckets.get(b))?.[x]||null}
  const rowText=r=>C([r?.search,r?.name,r?.brand,...(Array.isArray(r?.sellers)?r.sellers:[])].join(" "));
  function title(m,r){let t=C(m?.title)||C(r?.name);if(!t||/^TP[A-Z]/i.test(t)){const b=C(r?.brand),x=C(r?.search).replace(/^TP[A-Z]{2,8}-[A-Z0-9]{8,}\s*/i,"");t=b&&L(x).startsWith(L(b)+" ")?x.slice(b.length).trim():x||b}t=C(t).replace(/^\[[^\]]{1,28}\]\s*/,"").replace(/\b(?:factory price|hot sale|hot sell|best price|original authentic|global official version|wholesale price)\b/ig,"").replace(/\s+/g," ");return t.length>100?t.slice(0,97).trimEnd()+"…":t}
  function role(m,r,t){if(!m)return false;if(m.shopperType&&m.shopperType!==t)return false;const x=title(m,r);if(!x)return false;if(t==="phone"){if(m.isPhoneHandset===false||PF.test(x)||FIT.test(x))return false;if(PM.test(x))return true;if(PG.test(x)){PS.lastIndex=0;return(x.match(PS)||[]).length>=1}return false}const z=R[t];return!!z&&!z[1].test(x)&&z[0].test(x)}
  const queryOK=(x,q,t)=>broad(q,t)||tokens(q).every(k=>L(x).includes(k)),dynamic=g=>/tiktok/i.test(C(g?.seller))&&(g?.availability==="check-live"||g?.availability_dynamic===true),exact=g=>g?.destination_exact===true||/^(?:exact-tracked|exact-direct)$/i.test(C(g?.primary?.kind)),groups=m=>(Array.isArray(m?.sellerGroups)?m.sellerGroups:[]).filter(g=>seller(g?.seller)&&g?.availability!=="unavailable"&&!dynamic(g));
  function price(gs,t){const a=[],f=FLOOR[t]??.01;for(const g of gs)if(exact(g))for(const v of[g?.minPrice,g?.primary?.price]){const n=Number(v);if(n>=f&&n<=20000)a.push(n)}return a.length?Math.min(...a):0}
  function brand(m,r,x,t){const b=C(m?.brand||r?.brand);if(!b)return LABEL[t]||"Product";if(L(x).includes(L(b)))return b;if(t==="phone"){if(L(b)==="xiaomi"&&/\b(?:xiaomi|redmi)\b/i.test(x))return"Xiaomi";if(L(b)==="google"&&/\bpixel\b/i.test(x))return"Google";if(L(b)==="samsung"&&/\bgalaxy\b/i.test(x))return"Samsung";if(L(b)==="apple"&&/\biphone\b/i.test(x))return"Apple"}return LABEL[t]||"Product"}
  async function prep(r,t){if(!r?.tpid)return null;const m=await meta(r.tpid);if(!role(m,r,t))return null;const x=title(m,r);if(!queryOK(x,S.q,t))return null;const all=Array.isArray(m?.sellerGroups)?m.sellerGroups.filter(g=>seller(g?.seller)):[],gs=groups(m),ss=gs.length?[...new Set(gs.map(g=>C(g.seller)))]:all.length?[]:[...new Set((r.sellers||[]).filter(seller))];if(all.length&&!ss.length)return null;const route=C(m?.route).startsWith("/product/")?C(m.route):(suffix(r.tpid)?`/product/item--${suffix(r.tpid)}/`:"");if(!route)return null;return{r,m,t,title:x,brand:brand(m,r,x,t),image:goodImage(m?.image)?C(m.image):goodImage(r.image)?C(r.image):"",price:price(gs,t),route,sellers:ss,sellerCount:Math.max(1,ss.length||Number(r.sellerCount||0)),variants:Math.max(1,Number(r.variantCount||1)),desc:C(m?.summary)||`${LABEL[t]||"Product"} choice — compare details and seller offers before buying.`,score:Number(r.__score||0)}}
  async function load(t){const r=await fetch(`/data/search-v20-6/comparison-v20-6-4/browse-lite/${FILE[t]}.json?v=${V}`,{cache:"no-store"});if(!r.ok)throw Error(`catalogue ${t}: ${r.status}`);const j=await r.json();if(!Array.isArray(j?.products))throw Error("invalid catalogue");return j.products}
  function score(r,q,t){if(broad(q,t))return 100;const h=L(rowText(r)),ts=tokens(q);let n=0;for(const k of ts)if(h.includes(k))n++;return n===ts.length?300+n:n?80+n:0}
  function diversifyRows(rows){
    const buckets=new Map(),multi=[];
    for(const r of rows){
      const ss=[...new Set((Array.isArray(r?.sellers)?r.sellers:[]).map(C).filter(seller))];
      if(ss.length>1){multi.push(r);continue}
      const k=ss[0]||"Unknown";
      if(!buckets.has(k))buckets.set(k,[]);
      buckets.get(k).push(r);
    }
    const names=[...buckets.keys()].sort((a,b)=>{
      if(a==="Alibaba"&&b!=="Alibaba")return 1;
      if(b==="Alibaba"&&a!=="Alibaba")return -1;
      return (buckets.get(a)?.length||0)-(buckets.get(b)?.length||0);
    });
    const out=[],seen=new Set();
    for(const r of multi){out.push(r);seen.add(r.tpid)}
    let left=true,round=0;
    while(left&&round<rows.length){
      left=false;
      for(const n of names){
        const a=buckets.get(n)||[],take=n==="Alibaba"?3:1;
        for(let j=0;j<take;j++){
          const r=a[round*take+j];
          if(r){left=true;if(!seen.has(r.tpid)){out.push(r);seen.add(r.tpid)}}
        }
      }
      round++;
    }
    for(const r of rows)if(!seen.has(r.tpid))out.push(r);
    return out;
  }
  const filterRows=(a,q,t)=>diversifyRows(a.filter(r=>!Array.isArray(r?.sellers)||r.sellers.some(seller)).map(r=>({...r,__score:score(r,q,t)})).filter(r=>r.__score>0).sort((a,b)=>b.__score-a.__score||Number(b.sellerCount||0)-Number(a.sellerCount||0))),F=()=>({seller:C($("[data-filter-merchant]")?.value),price:C($("[data-filter-price]")?.value),sort:C($("[data-filter-sort]")?.value||"smart")});
  function itemOK(x){const f=F();if(f.seller&&!x.sellers.includes(f.seller))return false;if(f.price){const p=x.price;if(!(p>0))return false;if(f.price==="0-10"&&p>=10)return false;if(f.price==="10-25"&&(p<10||p>=25))return false;if(f.price==="25-50"&&(p<25||p>=50))return false;if(f.price==="50-100"&&(p<50||p>=100))return false;if(f.price==="100+"&&p<100)return false}return true}
  const sortItems=a=>{const s=F().sort;if(s==="price-low")return a.sort((x,y)=>(x.price||1e9)-(y.price||1e9));if(s==="price-high")return a.sort((x,y)=>(y.price||-1)-(x.price||-1));return a.sort((x,y)=>y.score-x.score||y.sellerCount-x.sellerCount||y.variants-x.variants)},saved=()=>{try{return new Set(JSON.parse(localStorage.getItem("trendpilot-v20-saved-tpids")||"[]"))}catch{return new Set()}},save=x=>localStorage.setItem("trendpilot-v20-saved-tpids",JSON.stringify([...x].slice(-100))),money=p=>p>0?`From US$${p.toLocaleString(undefined,{maximumFractionDigits:2})}`:"Check current price";
  function card(x,i){const sv=saved().has(x.r.tpid),img=x.image?`<img src="${E(x.image)}" alt="${E(x.title)}" loading="${i<2?"eager":"lazy"}" decoding="async" width="180" height="180" referrerpolicy="no-referrer">`:`<span class="tp78-fallback">${E((x.brand||"TP").slice(0,2).toUpperCase())}</span>`,sl=x.sellerCount===1?(x.sellers[0]||"1 seller"):`${x.sellerCount} sellers`;return`<article class="tp78-card" data-v2079-card="${E(x.r.tpid)}"><a class="tp78-media" href="${E(x.route)}" aria-label="View ${E(x.title)}">${img}</a><div class="tp78-body"><div class="tp78-top"><span class="tp78-brand">${E(x.brand)}</span><span class="tp78-source">${E(sl)}</span></div><h3><a href="${E(x.route)}">${E(x.title)}</a></h3><div class="tp78-price">${E(money(x.price))}</div><div class="tp78-meta"><span>${E(sl)}</span><span>•</span><span>${x.variants} variant${x.variants===1?"":"s"}</span></div><p class="tp78-description">${E(x.desc)}</p><div class="tp78-actions"><a class="tp78-view" href="${E(x.route)}">View product <span aria-hidden="true">→</span></a><a class="tp78-icon" href="${E(x.route)}#seller-offers" aria-label="View seller offers" title="Seller offers">≡</a><button class="tp78-icon${sv?" is-saved":""}" data-v2079-save="${E(x.r.tpid)}" type="button" aria-label="${sv?"Remove saved product":"Save product"}">${sv?"♥":"♡"}</button></div></div></article>`}
  function sellerOptions(){const s=$("[data-filter-merchant]");if(!s)return;const v=C(s.value),a=[...new Set(S.shown.flatMap(x=>x.sellers).filter(seller))].sort();s.innerHTML='<option value="">All sellers</option>'+a.map(x=>`<option value="${E(x)}">${E(x)}</option>`).join("");if(a.includes(v))s.value=v}
  function render(){const g=$("[data-v2078-product-grid]"),a=sortItems(S.shown.slice());g.innerHTML=a.length?a.map(card).join(""):'<div class="tp78-empty"><h3>No clean matches found.</h3><p>Try a model name or another product category.</p></div>';sellerOptions();const c=$("[data-v2078-results-count]");if(c)c.textContent=a.length?`${a.length} shown`:"No matches";const m=$("[data-v2078-load-more]");if(m)m.hidden=S.i>=S.list.length}
  async function batch(){if(S.busy)return;S.busy=true;const b=$("[data-v2078-load-more]");if(b){b.disabled=true;b.textContent="Loading…"}try{const a=[];while(a.length<S.size&&S.i<S.list.length){const ch=S.list.slice(S.i,S.i+10);S.i+=ch.length;for(const x of await Promise.all(ch.map(r=>prep(r,S.type))))if(x&&itemOK(x)){a.push(x);if(a.length>=S.size)break}}S.shown.push(...a);render()}finally{S.busy=false;if(b){b.disabled=false;b.textContent="Show more products"}}}
  function reset(){S.i=0;S.shown=[];const g=$("[data-v2078-product-grid]");if(g)g.innerHTML='<div class="tp78-loading">Checking clean product identities…</div>';batch().catch(fail)}
  async function generic(q){S.generic=true;const r=await fetch(`/api/products-v16-hybrid?q=${encodeURIComponent(q)}&limit=60&test=2079`,{cache:"no-store"});if(!r.ok)throw Error(`search ${r.status}`);const j=await r.json(),ts=tokens(q),a=[];for(const x of(j?.products||j?.results||j?.rows||j?.items||[])){const t=C(x?.name||x?.title||x?.productName),s=C(x?.advertiser||x?.seller||x?.merchant),u=C(x?.url||x?.affiliateUrl||x?.productUrl||x?.clickUrl),im=C(x?.image||x?.imageUrl||x?.thumbnail);if(!t||!seller(s)||!U(u)||!ts.every(k=>L(t).includes(k)))continue;a.push({t,s,u,im:U(im)?im:"",p:Number(x?.price)||0});if(a.length>=30)break}const g=$("[data-v2078-product-grid]");g.innerHTML=a.length?a.map((x,i)=>`<article class="tp78-card"><a class="tp78-media" href="${E(x.u)}" target="_blank" rel="nofollow sponsored noopener">${x.im?`<img src="${E(x.im)}" alt="${E(x.t)}" loading="${i<2?"eager":"lazy"}" width="180" height="180" referrerpolicy="no-referrer">`:'<span class="tp78-fallback">TP</span>'}</a><div class="tp78-body"><div class="tp78-top"><span class="tp78-brand">${E(x.s)}</span><span class="tp78-source">Seller result</span></div><h3><a href="${E(x.u)}" target="_blank" rel="nofollow sponsored noopener">${E(x.t)}</a></h3><div class="tp78-price">${E(x.p>0?`US$${x.p.toLocaleString(undefined,{maximumFractionDigits:2})}`:"Check current price")}</div><p class="tp78-description">Open the seller to confirm the exact product, current price, stock and delivery.</p><div class="tp78-actions"><a class="tp78-view" href="${E(x.u)}" target="_blank" rel="nofollow sponsored noopener">Check seller ↗</a><span></span><span></span></div></div></article>`).join(""):'<div class="tp78-empty"><h3>No matching products found.</h3><p>Try a broader product name.</p></div>';const c=$("[data-v2078-results-count]");if(c)c.textContent=a.length?`${a.length} shown`:"No matches";const m=$("[data-v2078-load-more]");if(m)m.hidden=true}
  async function search(q){q=C(q);if(!q)return;S.q=q;document.title=`${q} — Product results | TrendPilot AI`;S.type=type(q);S.generic=!S.type;S.i=0;S.shown=[];S.buckets.clear();const inp=$("[data-tp-finder-input]");if(inp)inp.value=q;if(S.type){const h=$("[data-v2078-results-title]"),p=$("[data-v2078-finder-status]");if(h)h.textContent=`${LABEL[S.type]} results for “${q}”`;if(p)p.textContent=S.type==="phone"?"Handset-only results. Cables, cases, batteries, fans, mounts, repair parts and live-only offers are excluded before rendering.":"Product-role validation is applied before each card is shown.";S.raw=await load(S.type);S.list=filterRows(S.raw,q,S.type);reset()}else{const h=$("[data-v2078-results-title]"),p=$("[data-v2078-finder-status]");if(h)h.textContent=`Search results for “${q}”`;if(p)p.textContent="Seller results are shown without guessing missing product identity.";await generic(q)}}
  const go=(q,scope="")=>{const p=new URLSearchParams();p.set("q",C(q));p.set("engine","v2064");p.set("ui","2079");if(C(scope))p.set("scope",C(scope));location.assign(`/find/?${p}`)};
  function fail(e){console.error("[TrendPilot V20.7.9]",e);const g=$("[data-v2078-product-grid]");if(g)g.innerHTML='<div class="tp78-empty"><h3>Products could not be displayed.</h3><p>Please try the search again.</p></div>';const c=$("[data-v2078-results-count]");if(c)c.textContent="Try again"}
  function toast(t){let n=$(".tp78-toast");if(!n){n=d.createElement("div");n.className="tp78-toast";d.body.appendChild(n)}n.textContent=t;n.classList.add("is-visible");setTimeout(()=>n.classList.remove("is-visible"),1800)}
  function chrome(){const n=$("[data-tp-nav]"),o=$("[data-tp-menu-button]"),c=$("[data-tp-menu-close]"),b=$("[data-tp-nav-backdrop]");if(n&&o){const set=v=>{n.classList.toggle("is-open",v);b?.classList.toggle("is-open",v);d.body.classList.toggle("tp-menu-open",v);o.setAttribute("aria-expanded",String(v))};set(false);o.onclick=()=>set(!n.classList.contains("is-open"));c?.addEventListener("click",()=>set(false));b?.addEventListener("click",()=>set(false));n.addEventListener("click",e=>{if(e.target.closest("a"))set(false)});d.addEventListener("keydown",e=>{if(e.key==="Escape")set(false)})}d.querySelectorAll("[data-year]").forEach(x=>x.textContent=new Date().getFullYear());d.querySelectorAll(".tp-bottom-nav a").forEach(a=>{const p=new URL(a.href,location.href).pathname.replace(/\/+$/,"")||"/",q=location.pathname.replace(/\/+$/,"")||"/";if(p===q||(q.startsWith("/find")&&p==="/find")){a.classList.add("active");a.setAttribute("aria-current","page")}})}
  function filterOpen(v){const p=$("[data-tp-filter-panel]"),b=$("[data-tp-filter-toggle]");if(!p||!b)return;p.classList.toggle("is-open",!!v);b.setAttribute("aria-expanded",String(!!v))}
  function events(){const f=$("[data-v2078-finder-form]");f?.addEventListener("submit",e=>{e.preventDefault();const q=C($("[data-tp-finder-input]",f)?.value);if(q)go(q,C($("[data-tp-finder-scope]",f)?.value))});d.addEventListener("click",e=>{const x=e.target.closest("[data-search-suggestion],[data-search-fill]");if(x){const q=C(x.dataset.searchSuggestion||x.dataset.searchFill);if(q){e.preventDefault();go(q,C(x.dataset.searchScope));return}}const s=e.target.closest("[data-v2079-save]");if(s){const a=saved(),id=C(s.dataset.v2079Save);if(a.has(id)){a.delete(id);s.classList.remove("is-saved");s.textContent="♡";toast("Removed from saved products")}else{a.add(id);s.classList.add("is-saved");s.textContent="♥";toast("Product saved")}save(a)}});$("[data-v2078-load-more]")?.addEventListener("click",()=>batch().catch(fail));d.addEventListener("change",e=>{if(e.target.matches("[data-filter-merchant],[data-filter-price],[data-filter-sort]")&&!S.generic)reset()});$("[data-tp-filter-toggle]")?.addEventListener("click",()=>filterOpen(!$("[data-tp-filter-panel]")?.classList.contains("is-open")));const m=matchMedia("(min-width:1040px)"),sync=()=>filterOpen(m.matches);sync();m.addEventListener?.("change",sync)}
  function start(){document.title="Find & Compare Products — TrendPilot AI";const h=$("[data-v2078-results-title]"),p=$("[data-v2078-finder-status]"),c=$("[data-v2078-results-count]"),g=$("[data-v2078-product-grid]");if(h)h.textContent="Search the product catalogue";if(p)p.textContent="Type a product, model or category above, or use one of the popular searches.";if(c)c.textContent="Ready";if(g)g.innerHTML='<div class="tp78-empty"><h3>What are you looking for?</h3><p>Search by product type or model. TrendPilot will keep accessories and unrelated listings out of exact-product results.</p></div>'}
  function boot(){d.body.classList.add("v207-public");chrome();events();const q=C(P.get("q"));q?search(q).catch(fail):start()}
  d.readyState==="loading"?d.addEventListener("DOMContentLoaded",boot,{once:true}):boot();
})();
