(() => {
  "use strict";
  const cfg=window.TRENDPILOT_SITE_CONFIG||{};
  const clean=v=>String(v??"").replace(/\s+/g," ").trim();
  const lower=v=>clean(v).toLowerCase();
  const esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#039;",'"':"&quot;"}[c]));
  const validUrl=v=>/^https?:\/\//i.test(String(v||""));
  const split=v=>clean(v).split("|").map(lower).filter(Boolean);
  const selected=new Map();
  const categoryOf=o=>{const h=lower([o.name,o.category,o.description].join(" "));if(h.includes("carplay"))return"wireless-carplay";if(/video editor|filmora|capcut/.test(h))return"video-editing";if(/supplier|wholesale|manufacturer|private label|custom logo/.test(h))return"sourcing";return clean(o.category)||"general"};
  function initMenu(){const b=document.querySelector('[data-menu-button]'),n=document.querySelector('[data-primary-nav]'),x=document.querySelector('[data-menu-backdrop]');if(!b||!n)return;const close=()=>{n.classList.remove('open');x?.classList.remove('open');document.body.classList.remove('menu-open');b.setAttribute('aria-expanded','false');b.setAttribute('aria-label','Open menu')};const open=()=>{n.classList.add('open');x?.classList.add('open');document.body.classList.add('menu-open');b.setAttribute('aria-expanded','true');b.setAttribute('aria-label','Close menu')};b.addEventListener('click',()=>n.classList.contains('open')?close():open());n.addEventListener('click',e=>{if(e.target.closest('[data-menu-close]')||e.target.closest('a'))close()});x?.addEventListener('click',close);document.addEventListener('keydown',e=>{if(e.key==='Escape')close()})}
  function initAnalytics(){if(!/^G-[A-Z0-9]+$/i.test(clean(cfg.ga4Id)))return;window.dataLayer=window.dataLayer||[];window.gtag=window.gtag||function(){dataLayer.push(arguments)};const s=document.createElement('script');s.async=true;s.src=`https://www.googletagmanager.com/gtag/js?id=${encodeURIComponent(cfg.ga4Id)}`;document.head.appendChild(s);gtag('js',new Date());gtag('config',cfg.ga4Id,{anonymize_ip:true})}
  function advertiserName(o){const v=clean(o?.advertiser||o?.network||'Seller');return lower(v)==='true'?'Geekbuying':v}
  function programmeMap(){const rows=window.TRENDPILOT_PROGRAM_STATUS?.programs||[];const m=new Map();rows.filter(p=>p.status==='active'&&p.public!==false).forEach(p=>m.set(lower(p.advertiser||p.name),p));return m}
  function allOffers(){const matches=window.TRENDPILOT_MATCHED_PRODUCTS||{};const pmap=programmeMap();const raw=Object.values(matches).flat().filter(Boolean);const seen=new Set();return raw.filter(o=>{const adv=lower(advertiserName(o));const key=lower(o.canonicalKey||o.productUrl||o.url||o.id||o.name);if(!key||seen.has(key)||!pmap.has(adv)||!clean(o.name)||!validUrl(o.url))return false;seen.add(key);o.__key=key;return true})}
  function passes(o,el){const hay=lower([o.name,o.description,o.category,o.brand].filter(Boolean).join(' ')),source=lower(el.dataset.advertiser),any=split(el.dataset.requiredAny),all=split(el.dataset.requiredAll),excluded=split(el.dataset.exclude),min=Number(el.dataset.minScore||75);if(source&&lower(advertiserName(o))!==source)return false;if(any.length&&!any.some(t=>hay.includes(t)))return false;if(all.length&&!all.every(t=>hay.includes(t)))return false;if(excluded.some(t=>hay.includes(t)))return false;if((Number(o.matchScore)||0)<min)return false;return true}
  function price(o){const n=Number(o.price);return Number.isFinite(n)&&n>0?`${clean(o.currency)||'USD'} ${n.toFixed(2)}`:'Check current price'}
  function image(o){return validUrl(o.image)?`<img src="${esc(o.image)}" alt="${esc(o.name)}" loading="lazy" decoding="async" referrerpolicy="no-referrer">`:`<span class="offer-fallback">${esc(advertiserName(o).slice(0,2).toUpperCase())}</span>`}
  function card(o,placement,compare=false){const adv=advertiserName(o),name=clean(o.name),key=clean(o.__key||o.url),pressed=selected.has(key);return `<article class="offer-card" data-offer-key="${esc(key)}"><a class="offer-media" href="${esc(o.url)}" target="_blank" rel="sponsored nofollow noopener" data-affiliate-outbound data-advertiser="${esc(adv)}" data-product-name="${esc(name)}" data-placement="${esc(placement)}">${image(o)}</a><div class="offer-body"><div class="offer-source"><span>${esc(adv)}</span><em>Current listing</em></div><h3>${esc(name)}</h3><div class="offer-meta"><strong>${esc(price(o))}</strong><span>Check shipping and returns</span></div><a class="button button-small button-brand" href="${esc(o.url)}" target="_blank" rel="sponsored nofollow noopener" data-affiliate-outbound data-advertiser="${esc(adv)}" data-product-name="${esc(name)}" data-placement="${esc(placement)}">View current offer ↗</a>${compare?`<button class="offer-compare" type="button" data-compare-key="${esc(key)}" aria-pressed="${pressed}">${pressed?'Selected':'Add to compare'}</button>`:''}</div></article>`}
  function renderOffers(){const offers=allOffers();document.querySelectorAll('[data-product-grid]').forEach(el=>{const limit=Math.max(1,Math.min(12,Number(el.dataset.limit)||4)),placement=clean(el.dataset.placement||'product-options'),compare=el.dataset.compareEnabled==='true';const rows=offers.filter(o=>passes(o,el)).sort((a,b)=>(Number(b.matchScore)||0)-(Number(a.matchScore)||0)||(Number(b.offerQuality)||0)-(Number(a.offerQuality)||0)).slice(0,limit);el.innerHTML=rows.length?rows.map(o=>card(o,placement,compare)).join(''):`<div class="offer-empty"><strong>No close product match is available right now.</strong><span>Try the product finder or check again after the catalogue refreshes.</span></div>`})}
  function guideScore(g,q){const words=lower(q).split(/\s+/).filter(Boolean),hay=lower([g.title,g.description,g.category,g.keywords].join(' '));return words.reduce((s,w)=>s+(hay.includes(w)?(lower(g.title).includes(w)?5:2):0),0)}
  function offerScore(o,q){const words=lower(q).split(/\s+/).filter(Boolean),hay=lower([o.name,o.description,o.category,o.brand,advertiserName(o)].join(' '));return words.reduce((s,w)=>s+(hay.includes(w)?(lower(o.name).includes(w)?6:2):0),0)+(Number(o.matchScore)||0)/50}
  function renderFinder(q){const box=document.querySelector('[data-finder-results]'),status=document.querySelector('[data-finder-status]');if(!box)return;const query=clean(q);const guides=(window.TRENDPILOT_SEARCH_INDEX||[]).map(g=>({...g,__score:guideScore(g,query)})).filter(g=>g.__score>0).sort((a,b)=>b.__score-a.__score).slice(0,6);const offers=allOffers().map(o=>({...o,__score:offerScore(o,query)})).filter(o=>o.__score>1.2).sort((a,b)=>b.__score-a.__score).slice(0,12);if(!query){box.innerHTML='';status.innerHTML='<strong>Start with a product or problem.</strong><span>Relevant guides and products will appear here.</span>';return}status.innerHTML=`<strong>Results for “${esc(query)}”</strong><span>${guides.length} guide${guides.length===1?'':'s'} and ${offers.length} current product option${offers.length===1?'':'s'} found.</span>`;let html='';if(guides.length)html+=`<section class="finder-group"><div class="finder-group-head"><h2>Helpful guides</h2><span>Start here if you are still deciding.</span></div><div class="finder-guide-grid">${guides.map(g=>`<article class="finder-guide"><small>${esc(g.type)} · ${esc(g.category)}</small><h3>${esc(g.title)}</h3><p>${esc(g.description)}</p><a href="${esc(g.url)}">Open guide →</a></article>`).join('')}</div></section>`;if(offers.length)html+=`<section class="finder-group"><div class="finder-group-head"><h2>Current product options</h2><span>Select up to three similar products to compare.</span></div><div class="offer-grid finder-offers">${offers.map(o=>card(o,'product-finder',true)).join('')}</div></section>`;if(!guides.length&&!offers.length)html=`<div class="offer-empty"><strong>We could not find a close match.</strong><span>Try a shorter product name, a category such as “video editor”, or request a comparison.</span><a class="button button-secondary" href="/contact.html">Request this product</a></div>`;box.innerHTML=html;bindCompareButtons()}
  function initFinder(){const form=document.querySelector('[data-finder-form]');if(!form)return;const input=form.querySelector('input[name=q]');const params=new URLSearchParams(location.search);input.value=params.get('q')||'';renderFinder(input.value);form.addEventListener('submit',e=>{e.preventDefault();const q=clean(input.value);history.replaceState(null,'',q?`?q=${encodeURIComponent(q)}`:location.pathname);renderFinder(q)});document.querySelectorAll('[data-query]').forEach(b=>b.addEventListener('click',()=>{input.value=b.dataset.query;form.requestSubmit()}))}
  function offerByKey(key){return allOffers().find(o=>clean(o.__key||o.url)===key)}
  function bindCompareButtons(){}
  function toggleCompare(key){const o=offerByKey(key);if(!o)return;if(selected.has(key))selected.delete(key);else{if(selected.size>=3){alert('You can compare up to three products. Remove one first.');return}const cats=[...selected.values()].map(categoryOf);if(cats.length&&cats[0]!==categoryOf(o)){alert('Choose products from the same category for a useful comparison.');return}selected.set(key,o)}updateCompareUI()}
  function updateCompareUI(){document.querySelectorAll('[data-compare-key]').forEach(b=>{const on=selected.has(b.dataset.compareKey);b.setAttribute('aria-pressed',String(on));b.textContent=on?'Selected':'Add to compare'});const d=document.querySelector('[data-compare-drawer]');if(!d)return;d.classList.toggle('open',selected.size>0);d.querySelector('[data-compare-count]').textContent=`${selected.size} of 3`;d.querySelector('[data-compare-selected]').innerHTML=[...selected.values()].map(o=>`<div class="compare-chip"><strong>${esc(o.name)}</strong><span>${esc(price(o))}</span></div>`).join('');d.querySelector('[data-compare-open]').disabled=selected.size<2}
  function openComparison(){const dlg=document.querySelector('[data-compare-dialog]'),box=document.querySelector('[data-compare-table]');if(!dlg||selected.size<2)return;const rows=[...selected.values()];box.innerHTML=`<h2>Compare selected products</h2><p>These listings are shown side by side. Confirm specifications, shipping and return terms on each seller page.</p><div class="compare-table-v7"><table><thead><tr><th>What to compare</th>${rows.map(o=>`<th><div class="compare-product-head">${image(o)}<strong>${esc(o.name)}</strong></div></th>`).join('')}</tr></thead><tbody><tr><th>Current price</th>${rows.map(o=>`<td>${esc(price(o))}</td>`).join('')}</tr><tr><th>Seller</th>${rows.map(o=>`<td>${esc(advertiserName(o))}</td>`).join('')}</tr><tr><th>Listing summary</th>${rows.map(o=>`<td>${esc(clean(o.description).slice(0,160)||'Open the product page to confirm the exact model and included items.')}</td>`).join('')}</tr><tr><th>Next step</th>${rows.map(o=>`<td><a href="${esc(o.url)}" target="_blank" rel="sponsored nofollow noopener">Check product details ↗</a></td>`).join('')}</tr></tbody></table></div>`;dlg.showModal()}
  function initCompare(){document.addEventListener('click',e=>{const b=e.target.closest('[data-compare-key]');if(b){e.preventDefault();toggleCompare(b.dataset.compareKey)}});document.querySelector('[data-compare-clear]')?.addEventListener('click',()=>{selected.clear();updateCompareUI()});document.querySelector('[data-compare-open]')?.addEventListener('click',openComparison);document.querySelector('[data-compare-close]')?.addEventListener('click',()=>document.querySelector('[data-compare-dialog]')?.close())}
  function bindAffiliateKeys(){const links=window.TRENDPILOT_LINKS||{};document.querySelectorAll('[data-affiliate-key]').forEach(a=>{const r=links[a.dataset.affiliateKey];if(!r)return;const u=clean(r.affiliateUrl);a.href=u||r.productUrl;a.target='_blank';a.rel='sponsored nofollow noopener';a.dataset.linkState=u?'partner':'official'});document.querySelectorAll('[data-pricing-key]').forEach(a=>{const r=links[a.dataset.pricingKey];if(!r)return;const u=clean(r.affiliateUrl);a.href=u||r.pricingUrl||r.productUrl;a.target='_blank';a.rel='sponsored nofollow noopener';a.dataset.linkState=u?'partner':'official'})}
  function track(a){const data={event:'outbound_product_click',page_path:location.pathname,advertiser:clean(a.dataset.advertiser||'Unknown'),product_name:clean(a.dataset.productName||a.textContent),placement:clean(a.dataset.placement||'unspecified'),destination_host:(()=>{try{return new URL(a.href).hostname}catch{return''}})()};window.dataLayer=window.dataLayer||[];window.dataLayer.push(data);if(typeof window.gtag==='function')window.gtag('event','outbound_product_click',data);if(validUrl(cfg.clickEndpoint)&&navigator.sendBeacon){try{navigator.sendBeacon(cfg.clickEndpoint,new Blob([JSON.stringify(data)],{type:'application/json'}))}catch{}}}
  function initTracking(){document.addEventListener('click',e=>{const a=e.target.closest('a[data-affiliate-outbound],a[rel~="sponsored"]');if(a)track(a)},{capture:true})}
  function fixImages(){document.addEventListener('error',e=>{const img=e.target;if(!(img instanceof HTMLImageElement))return;img.hidden=true;const p=img.parentElement;if(p&&!p.querySelector('.offer-fallback')){const s=document.createElement('span');s.className='offer-fallback';s.textContent='Product';p.appendChild(s)}},{capture:true})}
  document.addEventListener('DOMContentLoaded',()=>{initMenu();initAnalytics();bindAffiliateKeys();renderOffers();initFinder();initCompare();bindCompareButtons();initTracking();fixImages();document.querySelectorAll('[data-year]').forEach(e=>e.textContent=String(new Date().getFullYear()))});
})();