(()=>{"use strict";
const d=document,$=(s,r=d)=>r.querySelector(s),$$=(s,r=d)=>Array.from(r.querySelectorAll(s)),clean=v=>String(v??"").replace(/\s+/g," ").trim(),low=v=>clean(v).toLowerCase(),esc=v=>clean(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const BLOCK=new Set(["temu","joom","filamentpro","filamentpro eu cps","filamentpro-eu-cps"]);
let rows=[],shown=36;
function money(p){if(p.price==null)return"Check provider";try{return new Intl.NumberFormat(undefined,{style:"currency",currency:p.currency||"USD"}).format(p.price);}catch{return`${p.price} ${p.currency||""}`.trim();}}
function filters(){return{q:clean($("[data-ws-q]")?.value).toLowerCase(),platform:clean($("[data-ws-platform]")?.value),evidence:clean($("[data-ws-evidence]")?.value),sort:clean($("[data-ws-sort]")?.value||"evidence")};}
function matched(){const f=filters();let out=rows.filter(p=>(!f.q||`${p.name} ${p.seller} ${p.category} ${p.family}`.toLowerCase().includes(f.q))&&(!f.platform||p.platform===f.platform)&&(!f.evidence||(f.evidence==="moq"?p.moq!=null:f.evidence==="explicit"?p.evidenceScore>=4:p.evidenceScore>=2)));out=[...out];if(f.sort==="price")out.sort((a,b)=>(a.price??Infinity)-(b.price??Infinity));else if(f.sort==="moq")out.sort((a,b)=>(a.moq??Infinity)-(b.moq??Infinity));else if(f.sort==="platform")out.sort((a,b)=>pname(a).localeCompare(pname(b)));else out.sort((a,b)=>b.evidenceScore-a.evidenceScore);return out;}
const pname=p=>clean(p.platform||p.seller||"Marketplace");
function exitInfo(p){const platform=pname(p);if(p.destination_exact)return{label:`View exact listing on ${platform} ↗`,note:"Product-specific destination evidence is available for this record."};return{label:clean(p.destination_label)||`Search ${platform} for this product ↗`,note:clean(p.destination_warning)||"This destination may be broader than the exact product. Match the product name or model before ordering."};}
function card(p){const x=exitInfo(p);return`<article class="tp-wholesale-card"><div class="tp-wholesale-image">${p.image?`<img src="${esc(p.image)}" alt="${esc(p.name)}" loading="lazy">`:"Wholesale listing"}</div><div class="tp-wholesale-body"><span class="tp-wholesale-platform">${esc(pname(p))}</span><h2>${esc(p.name)}</h2><span class="tp-wholesale-evidence">${esc(p.evidence)}</span><div class="tp-wholesale-facts"><div><small>Listing price</small><b>${esc(money(p))}</b></div><div><small>MOQ</small><b>${p.moq!=null?esc(p.moq):"Confirm"}</b></div></div><p class="tp80-route-note">${esc(x.note)}</p><div class="tp-wholesale-actions"><button type="button" data-ws-quick="${esc(p.id)}">Quick view</button><a class="primary" href="${esc(p.url)}" target="_blank" rel="nofollow sponsored noopener">${esc(x.label)}</a></div></div></article>`;}
function render(){const out=matched(),host=$("[data-ws-results]"),count=$("[data-ws-count]");if(count)count.textContent=`${out.length} wholesale-capable result${out.length===1?"":"s"}`;if(host)host.innerHTML=out.slice(0,shown).map(card).join("")||'<div class="tp-empty"><h2>No matching wholesale records</h2><p>Try another product, marketplace or evidence level.</p></div>';const more=$("[data-ws-more]");if(more){more.hidden=out.length<=shown;more.textContent=`Show ${Math.min(36,out.length-shown)} more`;}}
function quick(p){let modal=$("[data-ws-modal]");if(!modal){modal=d.createElement("div");modal.className="tp-v14-modal";modal.hidden=true;modal.dataset.wsModal="";modal.innerHTML='<button class="tp-v14-modal-backdrop" data-ws-close type="button" aria-label="Close"></button><section class="tp-v14-modal-dialog"><button class="tp-v14-modal-close" data-ws-close type="button">×</button><div data-ws-modal-body></div></section>';d.body.appendChild(modal);}const body=$("[data-ws-modal-body]",modal),x=exitInfo(p);body.innerHTML=`<span class="tp-wholesale-platform">${esc(pname(p))}</span><h2>${esc(p.name)}</h2>${p.image?`<img src="${esc(p.image)}" alt="${esc(p.name)}" style="max-width:220px;width:100%;max-height:220px;object-fit:contain">`:""}<div class="tp-wholesale-facts"><div><small>Evidence</small><b>${esc(p.evidence)}</b></div><div><small>MOQ</small><b>${p.moq!=null?esc(p.moq):"Not stated"}</b></div><div><small>Listing price</small><b>${esc(money(p))}</b></div><div><small>Price basis</small><b>${esc(p.priceBasis)}</b></div></div><p>${esc(x.note)}</p><p>Before ordering, verify unit versus lot pricing, MOQ, sample availability, customization, shipping, tax and supplier terms.</p><div class="tp-wholesale-actions"><a class="primary" href="${esc(p.url)}" target="_blank" rel="nofollow sponsored noopener">${esc(x.label)}</a></div>`;modal.hidden=false;}
async function init(){try{const r=await fetch(`/data/wholesale-index.json?v=21.12.0`,{cache:"force-cache"}),data=r.ok?await r.json():{};rows=(data.products||[]).filter(p=>!BLOCK.has(low(p.platform||p.seller)));const platform=$("[data-ws-platform]");if(platform){[...new Set(rows.map(p=>p.platform).filter(Boolean))].sort().forEach(v=>platform.insertAdjacentHTML("beforeend",`<option value="${esc(v)}">${esc(v)}</option>`));}$$("[data-ws-q],[data-ws-platform],[data-ws-evidence],[data-ws-sort]").forEach(n=>n.addEventListener(n.tagName==="INPUT"?"input":"change",()=>{shown=36;render();}));$("[data-ws-more]")?.addEventListener("click",()=>{shown+=36;render();});d.addEventListener("click",e=>{const q=e.target.closest("[data-ws-quick]");if(q){const p=rows.find(x=>x.id===q.dataset.wsQuick);if(p)quick(p);return;}if(e.target.closest("[data-ws-close]")){const m=$("[data-ws-modal]");if(m)m.hidden=true;}});render();}catch(error){const host=$("[data-ws-results]");if(host)host.innerHTML='<div class="tp-empty"><h2>Wholesale catalogue unavailable</h2><p>Please try again shortly.</p></div>';}}
if(d.readyState==="loading")d.addEventListener("DOMContentLoaded",init,{once:true});else init();
})();
