(()=>{
const cfg={en:{title:p=>`Don’t lose this ticket offer${p?` · ${p}`:''}`,body:'We’ll email this offer so you can return to it anytime.',email:'Enter your email',save:'Get offer →',skip:'Continue without email',updates:'Alert me if the price changes',required:'Required',sending:'Opening offer…',error:'Could not save right now. You can still continue to the seller.',needAlert:'Please select the price alert to continue.',privacy:'No spam. Unsubscribe anytime.',quick:'✓ Takes 5 seconds'},ar:{title:p=>`لا تفقد عرض التذكرة${p?` · ${p}`:''}`,body:'سنرسل لك هذا العرض لتستطيع الرجوع إليه في أي وقت.',email:'أدخل بريدك الإلكتروني',save:'احصل على العرض ←',skip:'أكمل بدون بريد',updates:'نبّهني إذا تغير السعر',required:'مطلوب',sending:'جارٍ فتح العرض…',error:'تعذر حفظ العرض الآن، ويمكنك المتابعة إلى البائع.',needAlert:'اختر تنبيه تغيّر السعر للمتابعة.',privacy:'بدون رسائل مزعجة. يمكنك إلغاء الاشتراك في أي وقت.',quick:'✓ يستغرق 5 ثوانٍ'}};
const API='https://api.trendpilotchoice.com/save-search.php';
const lang=document.documentElement.lang&&document.documentElement.lang.startsWith('ar')?'ar':'en',t=cfg[lang];let pending=null;
const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const BIG={
'liverpool-v-manchester-united-2026':{file:'2023 07 31 arne mueseler 00001-Verbessert-RR (53106257591).jpg',labelAr:'أنفيلد — ملعب ليفربول',labelEn:'Anfield — Liverpool'},
'madrid-derby-2026':{file:'Wanda-Metropolitano.jpg',labelAr:'ملعب ميتروبوليتانو — مدريد',labelEn:'Metropolitano Stadium — Madrid'},
'north-london-derby-2026':{file:'Tottenham Hotspur Stadium.jpg',labelAr:'ملعب توتنهام هوتسبير — لندن',labelEn:'Tottenham Hotspur Stadium — London'},
'arsenal-v-manchester-city-2026':{file:'Emirates Stadium.jpg',labelAr:'ملعب الإمارات — لندن',labelEn:'Emirates Stadium — London'}
};
function params(){const p=new URLSearchParams(location.search);return{gclid:p.get('gclid')||'',utm_source:p.get('utm_source')||'',utm_campaign:p.get('utm_campaign')||'',utm_term:p.get('utm_term')||'',utm_content:p.get('utm_content')||''}}
function fire(name,data={}){window.dataLayer=window.dataLayer||[];window.dataLayer.push({event:name,...data})}
function addTicketDisclosure(){const hero=document.querySelector('.hero-copy'),lead=hero?.querySelector('.lead');if(!hero||!lead||hero.querySelector('.tp-ad-ticket-disclosure'))return;const copy=lang==='ar'?'TrendPilot دليل مستقل لمقارنة التذاكر ولا يبيع التذاكر ولا يُعد المزوّد الأساسي لها. بعض الروابط تقود إلى أسواق إعادة بيع، وقد تكون الأسعار أعلى من القيمة الاسمية.':'TrendPilot is an independent ticket comparison guide and does not sell tickets. We are not the primary ticket provider. Some links lead to resale marketplaces, where prices may be above face value.';const box=document.createElement('div');box.className='tp-ad-ticket-disclosure';box.textContent=copy;box.setAttribute('role','note');box.style.cssText='margin:14px 0 16px;padding:13px 15px;border:1px solid rgba(255,214,92,.48);border-radius:14px;background:rgba(255,214,92,.10);color:#fff;font-size:17px;font-weight:700;line-height:1.48;';lead.after(box)}
function enhanceBigMatch(){const slug=Object.keys(BIG).find(k=>location.pathname.includes('/events/'+k+'/'));if(!slug)return;const m=BIG[slug],hero=document.querySelector('.hero');if(hero&&!hero.querySelector('.tp-match-visual')){const fig=document.createElement('figure');fig.className='tp-match-visual';const src='https://commons.wikimedia.org/wiki/Special:FilePath/'+encodeURIComponent(m.file)+'?width=1600';const page='https://commons.wikimedia.org/wiki/File:'+encodeURIComponent(m.file).replace(/%20/g,'_');fig.innerHTML=`<img src="${src}" alt="${esc(lang==='ar'?m.labelAr:m.labelEn)}" loading="eager" fetchpriority="high"><figcaption>${esc(lang==='ar'?m.labelAr:m.labelEn)} · <a href="${page}" target="_blank" rel="noopener">Wikimedia Commons</a></figcaption>`;const copy=hero.querySelector('.hero-copy');copy?.querySelector('h1')?.after(fig)}
const first=document.querySelector('.price-card.best'),seller=first?.querySelector('.seller')?.textContent?.trim()||'LiveFootballTickets',price=first?.querySelector('.price')?.textContent?.trim()||'';
document.querySelectorAll('.final a[href^="http"],.sticky-buy a[href^="http"]').forEach(a=>{a.classList.add('price-link');a.dataset.seller=seller;a.dataset.price=price});
if(lang==='ar'){document.querySelectorAll('.area strong').forEach(x=>{if(x.textContent.trim()==='Budget')x.textContent='اقتصادي';if(x.textContent.trim()==='Better view')x.textContent='رؤية أفضل';if(x.textContent.trim()==='Premium')x.textContent='مميز'});const f=document.querySelector('.footer .shell');if(f)f.textContent='TrendPilot دليل مستقل للتخطيط والمقارنة وقد يحصل على عمولة من بعض الحجوزات المؤهلة. الأسعار والتوفر وشروط البائع قابلة للتغيير.';document.querySelectorAll('.updated').forEach(x=>{if(x.textContent.includes('28 Aug 2026'))x.textContent='آخر تحديث: 28 أغسطس 2026'})}
const cards=[...document.querySelectorAll('.price-card')];cards.forEach(card=>{const a=card.querySelector('a.price-link'),note=card.querySelector('.price-note');if(!a||!note)return;const u=a.getAttribute('href')||'';if(slug==='north-london-derby-2026'&&/^https:\/\/sportsevents365\.com\/?$/.test(u)){card.remove();const h=document.querySelector('.price-head h2');if(h)h.textContent=lang==='ar'?'اعرضنا هنا الرابط المباشر الذي تحققنا منه للمباراة نفسها.':'We are showing the direct match listing we could verify.'}else if(u.includes('/dock/team/')||u.includes('/events/venue/')){note.textContent=lang==='ar'?'صفحة بائع أوسع للمقارنة — تأكد من اختيار المباراة نفسها والسعر النهائي قبل الدفع.':'Broader seller listing — confirm the exact fixture and final checkout total before paying.'}});
if(!document.getElementById('tp-big-style')){const s=document.createElement('style');s.id='tp-big-style';s.textContent=`.tp-match-visual{margin:18px 0 16px;border-radius:20px;overflow:hidden;border:1px solid rgba(121,235,207,.28);background:#07131f}.tp-match-visual img{display:block;width:100%;aspect-ratio:16/9;object-fit:cover}.tp-match-visual figcaption{padding:8px 12px;color:#9aa9bd;font-size:12px;line-height:1.4}.tp-match-visual a{color:#9ddfce}.sticky-buy{padding:10px 14px}.sticky-buy .btn{min-height:50px;padding:12px 18px;font-size:18px}.price-card .price{direction:ltr;unicode-bidi:isolate}@media(max-width:720px){.hero h1{font-size:clamp(34px,10vw,52px);line-height:1.12}.lead{font-size:19px;line-height:1.7}.tp-ad-ticket-disclosure{font-size:15px!important}.card{border-radius:22px}.sticky-buy .btn{font-size:17px}.footer{padding-bottom:92px}}`;document.head.appendChild(s)}}
function build(){const d=document.createElement('div');d.id='tp-save-overlay';d.innerHTML=`<div class="tp-save-card" role="dialog" aria-modal="true" aria-labelledby="tp-save-title"><button class="tp-save-x" type="button" aria-label="Close">×</button><div class="tp-save-kicker">TrendPilot</div><h3 id="tp-save-title"></h3><p class="tp-save-body"></p><div class="tp-save-offer"></div><form><input type="email" name="email" autocomplete="email" required placeholder="${t.email}"><div class="tp-save-quick">${t.quick}</div><label class="tp-save-check"><input type="checkbox" name="updates" value="1" required><span>${t.updates} <b class="tp-required">${t.required}</b></span></label><button class="tp-save-primary" type="submit">${t.save}</button><button class="tp-save-skip" type="button">${t.skip}</button><small>🔒 ${t.privacy}</small><div class="tp-save-status" aria-live="polite"></div></form></div>`;document.body.appendChild(d);d.querySelector('.tp-save-x').onclick=()=>close(false);d.querySelector('.tp-save-skip').onclick=()=>close(true);d.addEventListener('click',e=>{if(e.target===d)close(false)});d.querySelector('form').addEventListener('submit',submit);return d}
let overlay;
function meta(link){const card=link.closest('.price-card');return{seller:link.dataset.seller||card?.querySelector('.seller')?.textContent?.trim()||'Ticket seller',price:link.dataset.price||card?.querySelector('.price')?.textContent?.trim()||''}}
function open(link){pending=link;overlay=overlay||build();const {seller,price}=meta(link);overlay.querySelector('#tp-save-title').textContent=t.title(price);overlay.querySelector('.tp-save-body').textContent=t.body;overlay.querySelector('.tp-save-offer').innerHTML=`<strong>${esc(seller)}</strong><span>${esc(price)}</span>`;overlay.querySelector('.tp-save-status').textContent='';overlay.querySelector('form').reset();overlay.classList.add('show');document.documentElement.classList.add('tp-modal-open');fire('SELLER_INTENT',{seller,price})}
function go(){if(!pending)return;const href=pending.href;pending=null;window.open(href,'_blank','noopener')}
function close(continueSeller){overlay?.classList.remove('show');document.documentElement.classList.remove('tp-modal-open');if(continueSeller)go();else pending=null}
async function submit(e){e.preventDefault();if(!pending)return;const f=e.currentTarget,btn=f.querySelector('.tp-save-primary'),status=f.querySelector('.tp-save-status'),{seller,price}=meta(pending);if(!f.updates.checked){status.textContent=t.needAlert;f.updates.focus();return}const offer_url=pending.href;btn.disabled=true;btn.textContent=t.sending;status.textContent='';try{const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({email:f.email.value.trim(),updates:true,lang,seller,price,offer_url,page_url:location.href,tracking:params()})});const j=await r.json().catch(()=>({}));if(!r.ok||!j.ok)throw new Error(j.error||'save_failed');fire('EMAIL_SAVE',{seller,price,lead_id:j.lead_id||''});pending=null;overlay?.classList.remove('show');document.documentElement.classList.remove('tp-modal-open');location.assign(offer_url)}catch(_){status.textContent=t.error;btn.disabled=false;btn.textContent=t.save}}
document.addEventListener('click',e=>{const a=e.target.closest('a.price-link');if(!a)return;if(e.metaKey||e.ctrlKey||e.shiftKey||e.altKey)return;e.preventDefault();open(a)});
const ready=()=>{addTicketDisclosure();enhanceBigMatch();const p=new URLSearchParams(location.search);if(p.get('return')==='email-buy'){const lead=p.get('lead')||'';if(/^[a-f0-9]{16}$/i.test(lead)){fire('EMAIL_BUY_RETURN',{lead_id:lead,seller:p.get('seller')||''});location.replace('https://api.trendpilotchoice.com/go.php?lead='+encodeURIComponent(lead));return}}if(p.get('return')==='email'){fire('EMAIL_RETURN',{lead_id:p.get('lead')||'',seller:p.get('seller')||''});setTimeout(()=>document.getElementById('prices')?.scrollIntoView({behavior:'smooth'}),250)}};
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',ready,{once:true}):ready();
})();